repos:
  - repo: local
    hooks:
      - id: semgrep
        name: Semgrep Analysis
        entry: docker compose run --rm semgrep
        language: system
        pass_filenames: false

      - id: sonar-scanner
        name: SonarQube Analysis
        entry: sonar-scanner.bat
        args:
          - -Dsonar.projectKey=llm4sast
          - -Dsonar.sources=.
          - -Dsonar.host.url=http://localhost:9000
          - -Dsonar.login=sqp_0e63a60f61e7977b02928be29a51ad2bb41d6734
        language: system
        pass_filenames: false

      - id: sonarqube_export
        name: Export SonarQube JSON
        entry: docker compose --env-file .env run --rm sonarqube-export
        language: system
        pass_filenames: false

      - id: llama-llm
        name: LLM Data Sensitive Detection
        entry: python .\scripts\run_llm.py
        language: system
        pass_filenames: false