repos:
  - repo: local
    hooks:
      - id: semgrep
        name: Semgrep Analysis
        entry: docker compose run --rm semgrep
        language: system
        pass_filenames: false

      - id: sonarqube
        name: SonarQube Analysis
        entry: docker compose run --rm sonarscanner
        language: system
        pass_filenames: false

      - id: sonarqube_export
        name: Export SonarQube JSON
        entry: docker compose run --rm sonarqube-export
        language: system
        pass_filenames: false

      - id: llama-llm
        name: LLM Data Sensitive Detection
        entry: python3 .\/scripts\/run_llm.py
        language: system
        pass_filenames: false
