repos:
  - repo: local
    hooks:
      # 1) Run Semgrep in Docker
      - id: semgrep
        name: Semgrep Analysis
        entry: docker compose --env-file .env run --rm semgrep
        language: system
        pass_filenames: false

      # 2) Minify Semgrep report
      - id: semgrep-minifier
        name: Semgrep report minifier
        entry: python scripts/semgrep_minifier.py
        language: system
        pass_filenames: false

      # 3) SonarQube Analysis
      #    We rely on environment variables and the docker-compose
      #    "sonarscanner" service to handle any -Dsonar.* properties.
      - id: sonar-scanner
        name: SonarQube Analysis
        entry: docker compose --env-file .env run --rm sonarscanner
        language: system
        pass_filenames: false

      # 4) Export SonarQube JSON
      - id: sonarqube_export
        name: Export SonarQube JSON
        entry: docker run --rm -v "$(pwd)/reports:/reports" curlimages/curl:latest -v -u "sqp_2577b60b9153d2bfddc3571e74b2cbc513298810" "http://host.docker.internal:9000/api/issues/search?componentKeys=llm4sast&types=VULNERABILITY,BUG,CODE_SMELL&ps=500" -o /reports/sonarqube_report.jso
        language: system
        pass_filenames: false

      # 5) LLM Data Sensitive Detection
      - id: llama-llm
        name: LLM Data Sensitive Detection
        entry: python scripts/run_llm.py
        language: system
        pass_filenames: false