services:
  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=${SONAR_ES_BOOTSTRAP_CHECKS_DISABLE}
      - SONAR_JDBC_URL=${SONAR_JDBC_URL}
      - SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=${SONAR_JDBC_USERNAME}
      - POSTGRES_PASSWORD=${SONAR_JDBC_PASSWORD}
      - POSTGRES_DB=sonar
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SONAR_JDBC_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  semgrep:
    image: semgrep/semgrep:latest
    container_name: semgrep
    environment:
      - SEMGREP_APP_TOKEN=${SEMGREP_APP_TOKEN}
    volumes:
      - .:/src
    working_dir: /src
    command: >
      semgrep scan --config auto --json --output reports/semgrep_report.json
      src/BenchmarkJava/src/main/java/org/owasp/benchmark/testcode_tmp

  sonarscanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonarscanner
    depends_on:
    - sonarqube
    volumes:
    - ./src/BenchmarkJava:/project
    - ./reports:/project/reports
    working_dir: /project
    environment:
     SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
     SONAR_HOST_URL: ${SONAR_HOST_URL}
     SONAR_LOGIN: ${SONAR_LOGIN}
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh", "-c"]
    command: >
     echo "SonarQube is UP. Starting scanner..." &&
     sonar-scanner


  sonarqube-export:
    image: curlimages/curl:latest
    container_name: sonarqube-export
    volumes:
      - ./reports:/reports
    entrypoint: ["/bin/sh", "-c"]
    command: >
      curl -v -u "sqp_2577b60b9153d2bfddc3571e74b2cbc513298810" "http://host.docker.internal:9000/api/issues/search?componentKeys=llm4sast&types=VULNERABILITY,BUG,CODE_SMELL&ps=500" -o /reports/sonarqube_report.jso


  pre-commit:
    image: python:3.9
    container_name: pre-commit
    volumes:
      - .:/repo
      - ./reports:/repo/reports
    working_dir: /repo
    entrypoint: ["/bin/sh", "-c"]
    command: >
      echo "Running pre-commit hooks..." &&
      pre-commit run --all-files &&
      echo "Pre-commit checks completed."

volumes:
  sonarqube_data:
  sonarqube_extensions:
  db_data:
  semgrep_rules: