# Project identification
sonar.projectKey=llm4sast
sonar.projectName=llm4sast
sonar.projectVersion=1.0
# Folder location inside the container
sonar.sources=src/main/java/org/owasp/benchmark/testcode_low
sonar.java.binaries=target/classes
sonar.exclusions=**/node_modules/**, **/reports/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_2577b60b9153d2bfddc3571e74b2cbc513298810